Repository gooddata/gooddata-java, pull requests merged in 2018-04, with the labels that each got.

#594 support for execution of visualization object
  src/main/java/com/gooddata/GoodData.java
  src/main/java/com/gooddata/executeafm/ExecuteAfmService.java
  src/main/java/com/gooddata/executeafm/VisualizationExecution.java
  src/main/java/com/gooddata/executeafm/afm/ExpressionFilter.java
  src/main/java/com/gooddata/md/visualization/VisualizationConverter.java
  src/main/java/com/gooddata/md/visualization/VisualizationObject.java
  src/test/groovy/com/gooddata/executeafm/ExecuteAfmServiceIT.groovy
  src/test/groovy/com/gooddata/executeafm/VisualizationExecutionTest.groovy
  src/test/groovy/com/gooddata/executeafm/afm/ExpressionFilterTest.groovy
  src/test/groovy/com/gooddata/md/visualization/VisualizationConverterTest.groovy
  src/test/java/com/gooddata/executeafm/ExecuteAfmServiceAT.java
  src/test/resources/executeafm/visualizationExecution.json
  src/test/resources/executeafm/visualizationExecutionFull.json
Labels: merge

#603 support irregular query type plurals in find by query resource
  src/main/java/com/gooddata/md/MetadataService.java
  src/test/java/com/gooddata/md/MetadataServiceTest.java
Labels: enhancement, merge

#608 Make `release.sh` Mac compatible
  release.sh
Labels: trivial
