Repository gooddata/gooddata-java, pull requests merged in 2018-07, with the labels that each got.

#626 introduce totals measure sort locator in the execute AFM
  src/main/java/com/gooddata/executeafm/resultspec/LocatorItem.java
  src/main/java/com/gooddata/executeafm/resultspec/TotalLocatorItem.java
  src/test/groovy/com/gooddata/executeafm/resultspec/TotalLocatorItemTest.groovy
  src/test/resources/executeafm/resultspec/totalLocatorItem.json
Labels: enhancement, merge

#628 Add support for new arithmetic measure definition
  src/main/java/com/gooddata/executeafm/afm/ArithmeticMeasureDefinition.java
  src/main/java/com/gooddata/executeafm/afm/MeasureDefinition.java
  src/test/groovy/com/gooddata/executeafm/afm/ArithmeticMeasureDefinitionTest.groovy
  src/test/resources/executeafm/afm/arithmeticMeasureDefinition.json
Labels: enhancement

#630 rename measures to measureIdentifiers in ArithmeticMeasureDefinition
  src/main/java/com/gooddata/executeafm/afm/ArithmeticMeasureDefinition.java
  src/test/groovy/com/gooddata/executeafm/afm/ArithmeticMeasureDefinitionTest.groovy
  src/test/resources/executeafm/afm/arithmeticMeasureDefinition.json
Labels: bug, merge

#631 bump version in README before mvn release
  release.sh
Labels: merge, trivial

#633 Raise dependency versions (with bugfixes)
  pom.xml
Labels: bug
