Repository gooddata/gooddata-java, pull requests merged in 2018-06, with the labels that each got.

#613 Introduce support for Over period and Previous period measure definition
  src/main/java/com/gooddata/executeafm/afm/MeasureDefinition.java
  src/main/java/com/gooddata/executeafm/afm/ObjIdentifierUtilities.java
  src/main/java/com/gooddata/executeafm/afm/ObjQualifierConverter.java
  src/main/java/com/gooddata/executeafm/afm/OverPeriodDateAttribute.java
  src/main/java/com/gooddata/executeafm/afm/OverPeriodMeasureDefinition.java
  src/main/java/com/gooddata/executeafm/afm/PopMeasureDefinition.java
  src/main/java/com/gooddata/executeafm/afm/PreviousPeriodDateDataSet.java
  src/main/java/com/gooddata/executeafm/afm/PreviousPeriodMeasureDefinition.java
  src/main/java/com/gooddata/executeafm/afm/SimpleMeasureDefinition.java
  src/main/java/com/gooddata/md/visualization/VOPopMeasureDefinition.java
  src/test/groovy/com/gooddata/executeafm/afm/MeasureDefinitionTest.groovy
  src/test/groovy/com/gooddata/executeafm/afm/ObjIdentifierUtilitiesTest.groovy
  src/test/groovy/com/gooddata/executeafm/afm/OverPeriodDateAttributeTest.groovy
  src/test/groovy/com/gooddata/executeafm/afm/OverPeriodMeasureDefinitionTest.groovy
  src/test/groovy/com/gooddata/executeafm/afm/PopMeasureDefinitionTest.groovy
  src/test/groovy/com/gooddata/executeafm/afm/PreviousPeriodDateDataSetTest.groovy
  src/test/groovy/com/gooddata/executeafm/afm/PreviousPeriodMeasureDefinitionTest.groovy
  src/test/groovy/com/gooddata/executeafm/afm/SimpleMeasureDefinitionTest.groovy
  src/test/resources/executeafm/afm/overPeriodDateAttribute.json
  src/test/resources/executeafm/afm/overPeriodMeasureDefinition.json
  src/test/resources/executeafm/afm/overPeriodMeasureDefinitionWithTwoAttributes.json
  src/test/resources/executeafm/afm/popMeasureDefinitionWithOffset.json
  src/test/resources/executeafm/afm/previousPeriodDateDataSet.json
  src/test/resources/executeafm/afm/previousPeriodMeasureDefinition.json
  src/test/resources/executeafm/afm/previousPeriodMeasureDefinitionWithTwoDataSets.json
Labels: enhancement

#614 Upgrade to httpclient 4.5.5
  README.md
  pom.xml
Labels: enhancement

#615 Use gooddata-rest-common 1.2.1
  pom.xml
Labels: trivial

#618 Use patched jackson-databind dependency
  pom.xml
Labels: bug

#623 Introduce interface for derived measures
  src/main/java/com/gooddata/executeafm/afm/DerivedMeasureDefinition.java
  src/main/java/com/gooddata/executeafm/afm/OverPeriodMeasureDefinition.java
  src/main/java/com/gooddata/executeafm/afm/PopMeasureDefinition.java
  src/main/java/com/gooddata/executeafm/afm/PreviousPeriodMeasureDefinition.java
Labels: enhancement

#624 Fix releasing
  release.sh
Labels: bug
