Repository gooddata/gooddata-java, pull requests merged in 2018-10, with the labels that each got.

#642 Remove acceptance test for Datawarehouse S3 creds
  src/test/java/com/gooddata/warehouse/WarehouseServiceAT.java
Labels: trivial

#643 Fix dependency in WarehouseServiceAT
  src/test/java/com/gooddata/warehouse/WarehouseServiceAT.java
Labels: trivial

#654 In zendesk4 connector, we need to know if scheduler start a reload of a project
  src/main/java/com/gooddata/connector/Zendesk4ProcessExecution.java
  src/test/java/com/gooddata/connector/Zendesk4ProcessExecutionTest.java
  src/test/resources/connector/process-execution-reload.json
Labels: enhancement

#672 Added missing MD obj flags (AbstractObj.Meta.flags) property
  src/main/java/com/gooddata/md/AbstractObj.java
  src/main/java/com/gooddata/md/Meta.java
  src/main/java/com/gooddata/md/ScheduledMail.java
  src/main/java/com/gooddata/project/Project.java
  src/test/java/com/gooddata/md/MetaTest.java
  src/test/java/com/gooddata/md/ObjTest.java
  src/test/resources/md/meta-withFlags.json
Labels: bug
