Repository gooddata/gooddata-java, pull requests merged in 2019-06, with the labels that each got.

#792 test project feature flag change
  gooddata-java/src/test/java/com/gooddata/sdk/service/featureflag/FeatureFlagServiceAT.java
Labels: trivial

#802 make static properties of ExecuteAfmService public
  gooddata-java/src/main/java/com/gooddata/sdk/service/executeafm/ExecuteAfmService.java
Labels: enhancement, trivial

#801 add support for profile separator settings
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/account/SeparatorSettings.java
  gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/account/SeparatorSettingsTest.groovy
  gooddata-java-model/src/test/resources/account/separators.json
  gooddata-java/src/main/java/com/gooddata/sdk/service/account/AccountService.java
  gooddata-java/src/test/java/com/gooddata/sdk/service/account/AccountServiceAT.java
  gooddata-java/src/test/java/com/gooddata/sdk/service/account/AccountServiceIT.java
  gooddata-java/src/test/resources/account/separators.json
Labels: enhancement

#800 add support for KPI and analytical dashboard metadata
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/md/dashboard/AnalyticalDashboard.java
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/md/dashboard/Kpi.java
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/md/dashboard/KpiAlert.java
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/md/dashboard/filter/AttributeFilterReference.java
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/md/dashboard/filter/DashboardAttributeFilter.java
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/md/dashboard/filter/DashboardDateFilter.java
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/md/dashboard/filter/DashboardFilter.java
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/md/dashboard/filter/DashboardFilterContext.java
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/md/dashboard/filter/DateFilterReference.java
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/md/dashboard/filter/FilterReference.java
  gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/md/dashboard/AnalyticalDashboardTest.groovy
  gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/md/dashboard/KpiAlertTest.groovy
  gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/md/dashboard/KpiTest.groovy
  gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/md/dashboard/filter/AttributeFilterReferenceTest.groovy
  gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/md/dashboard/filter/DashboardAttributeFilterTest.groovy
  gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/md/dashboard/filter/DashboardDateFilterTest.groovy
  gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/md/dashboard/filter/DashboardFilterContextTest.groovy
  gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/md/dashboard/filter/DateFilterReferenceTest.groovy
  gooddata-java-model/src/test/resources/md/dashboard/analyticalDashboard-new.json
  gooddata-java-model/src/test/resources/md/dashboard/analyticalDashboard-out.json
  gooddata-java-model/src/test/resources/md/dashboard/filter/attributeFilterReference.json
  gooddata-java-model/src/test/resources/md/dashboard/filter/dashboardAttributeFilter.json
  gooddata-java-model/src/test/resources/md/dashboard/filter/dashboardDateFilter-absolute.json
  gooddata-java-model/src/test/resources/md/dashboard/filter/dashboardDateFilter-relative.json
  gooddata-java-model/src/test/resources/md/dashboard/filter/dateFilterReference.json
  gooddata-java-model/src/test/resources/md/dashboard/filter/filterContext-new.json
  gooddata-java-model/src/test/resources/md/dashboard/filter/filterContext-out.json
  gooddata-java-model/src/test/resources/md/dashboard/kpi-new.json
  gooddata-java-model/src/test/resources/md/dashboard/kpi-out.json
  gooddata-java-model/src/test/resources/md/dashboard/kpiAlert-new.json
  gooddata-java-model/src/test/resources/md/dashboard/kpiAlert-out.json
Labels: enhancement

#805 Do not fail on missing spring-retry if retry isn't configured
  src/main/java/com/gooddata/GoodData.java
  src/main/java/com/gooddata/retry/RetryableRestTemplate.java
Labels: bug

#809 Add RC how-to to CONTRIBUTING guide
  CONTRIBUTING.md
Labels: trivial

#814 Clean up the endpoint and headers usage
  gooddata-java/src/main/java/com/gooddata/sdk/service/GoodData.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/GoodDataSettings.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/export/ExportService.java
  gooddata-java/src/test/groovy/com/gooddata/sdk/service/GoodDataITBase.groovy
  gooddata-java/src/test/groovy/com/gooddata/sdk/service/GoodDataSettingsTest.groovy
  gooddata-java/src/test/groovy/com/gooddata/sdk/service/export/ExportServiceIT.groovy
  gooddata-java/src/test/groovy/com/gooddata/sdk/service/export/ExportServiceTest.groovy
  gooddata-java/src/test/java/com/gooddata/sdk/service/AbstractGoodDataAT.java
  gooddata-java/src/test/java/com/gooddata/sdk/service/AbstractGoodDataIT.java
  gooddata-java/src/test/java/com/gooddata/sdk/service/GoodDataSettingsTest.java
  gooddata-java/src/test/java/com/gooddata/sdk/service/export/ExportServiceAT.java
  gooddata-java/src/test/java/com/gooddata/sdk/service/export/ExportServiceIT.java
  gooddata-java/src/test/java/com/gooddata/sdk/service/export/ExportServiceTest.java
Labels: backward incompatible, trivial
