Repository gooddata/gooddata-java, pull requests merged in 2019-07, with the labels that each got.

#818 Remove cherry-pick leftovers from master branch
  src/test/groovy/com/gooddata/retry/RetrySettingsTest.groovy
  src/test/groovy/com/gooddata/retry/RetryableRestTemplateTest.groovy
Labels: trivial

#820 Migrate to slf4j-simple logger in tests
  pom.xml
  src/test/resources/log4j.properties
  src/test/resources/simplelogger.properties
Labels: bug

#816 Use standard cookie specs
  src/main/java/com/gooddata/GoodData.java
Labels: enhancement

#813 Decouple from httpclient
  findBugsFilter.xml
  gooddata-java/src/main/java/com/gooddata/sdk/service/AbstractPollHandler.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/Authentication.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/DeprecationWarningRequestInterceptor.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/GoodData.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/GoodDataRestProvider.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/GoodDataServices.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/HeaderSettingRequestInterceptor.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/account/AccountService.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/authentication/LoginPasswordAuthentication.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/authentication/SstAuthentication.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/dataload/processes/ProcessService.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/dataset/DatasetService.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/executeafm/ExecuteAfmService.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/featureflag/FeatureFlagService.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/gdc/DataStoreService.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/gdc/GdcService.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/httpcomponents/GoodDataHttpClientBuilder.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/httpcomponents/LoginPasswordGoodDataRestProvider.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/httpcomponents/SingleEndpointGoodDataRestProvider.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/httpcomponents/SstGoodDataRestProvider.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/lcm/LcmService.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/md/maintenance/ExportImportService.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/notification/NotificationService.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/project/model/ModelService.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/projecttemplate/ProjectTemplateService.java
  gooddata-java/src/main/java/com/gooddata/sdk/service/warehouse/WarehouseService.java
  gooddata-java/src/test/groovy/com/gooddata/sdk/service/GoodDataITBase.groovy
  gooddata-java/src/test/groovy/com/gooddata/sdk/service/GoodDataServicesTest.groovy
  gooddata-java/src/test/groovy/com/gooddata/sdk/service/httpcomponents/LoginPasswordGoodDataRestProviderTest.groovy
  gooddata-java/src/test/groovy/com/gooddata/sdk/service/httpcomponents/SingleEndpointGoodDataRestProviderTest.groovy
  gooddata-java/src/test/groovy/com/gooddata/sdk/service/httpcomponents/SstGoodDataRestProviderTest.groovy
  gooddata-java/src/test/java/com/gooddata/sdk/service/AbstractGoodDataAT.java
  gooddata-java/src/test/java/com/gooddata/sdk/service/AbstractGoodDataIT.java
  gooddata-java/src/test/java/com/gooddata/sdk/service/authentication/LoginPasswordAuthenticationTest.java
  gooddata-java/src/test/java/com/gooddata/sdk/service/authentication/SstAuthenticationTest.java
  pom.xml
Labels: backward incompatible, enhancement

#824 Remove support for Coupa and Pardot connector
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/connector/ConnectorType.java
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/connector/CoupaInstance.java
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/connector/CoupaInstances.java
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/connector/CoupaProcessExecution.java
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/connector/CoupaSettings.java
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/connector/PardotProcessExecution.java
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/connector/PardotSettings.java
  gooddata-java-model/src/test/java/com/gooddata/sdk/model/connector/CoupaInstanceTest.java
  gooddata-java-model/src/test/java/com/gooddata/sdk/model/connector/CoupaInstancesTest.java
  gooddata-java-model/src/test/java/com/gooddata/sdk/model/connector/CoupaProcessExecutionTest.java
  gooddata-java-model/src/test/java/com/gooddata/sdk/model/connector/CoupaSettingsTest.java
  gooddata-java-model/src/test/java/com/gooddata/sdk/model/connector/PardotProcessExecutionTest.java
  gooddata-java-model/src/test/java/com/gooddata/sdk/model/connector/PardotSettingsTest.java
  gooddata-java-model/src/test/resources/connector/coupa_instance.json
  gooddata-java-model/src/test/resources/connector/coupa_instances.json
  gooddata-java-model/src/test/resources/connector/settings-coupa.json
  gooddata-java-model/src/test/resources/connector/settings-pardot.json
  gooddata-java/src/main/java/com/gooddata/sdk/service/connector/ConnectorService.java
  gooddata-java/src/test/java/com/gooddata/sdk/service/connector/ConnectorServiceIT.java
  gooddata-java/src/test/resources/connector/coupa_instances-empty.json
Labels: backward incompatible
