Repository gooddata/gooddata-java, pull requests merged in 2019-02, with the labels that each got.

#723 Introduce AttributeFilters' support for value filtering
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/executeafm/afm/AttributeFilterElements.java
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/executeafm/afm/NegativeAttributeFilter.java
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/executeafm/afm/PositiveAttributeFilter.java
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/executeafm/afm/SimpleAttributeFilterElements.java
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/executeafm/afm/UriAttributeFilterElements.java
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/executeafm/afm/ValueAttributeFilterElements.java
  gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/executeafm/afm/NegativeAttributeFilterTest.groovy
  gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/executeafm/afm/PositiveAttributeFilterTest.groovy
  gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/executeafm/afm/SimpleMeasureDefinitionTest.groovy
  gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/executeafm/afm/UriAttributeFilterElementsTest.groovy
  gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/executeafm/afm/ValueAttributeFilterElementsTest.groovy
  gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/md/visualization/VisualizationConverterTest.groovy
  gooddata-java-model/src/test/resources/executeafm/afm/negativeAttributeFilterUris.json
  gooddata-java-model/src/test/resources/executeafm/afm/negativeAttributeFilterValues.json
  gooddata-java-model/src/test/resources/executeafm/afm/positiveAttributeFilterUris.json
  gooddata-java-model/src/test/resources/executeafm/afm/positiveAttributeFilterValues.json
  gooddata-java-model/src/test/resources/executeafm/afm/uriAttributeFilterElements.json
  gooddata-java-model/src/test/resources/executeafm/afm/valueAttributeFilterElements.json
Labels: enhancement

#725 Introduce recovery related fields in Zendesk4ProcessExecution
  src/main/java/com/gooddata/connector/Zendesk4ProcessExecution.java
  src/test/java/com/gooddata/connector/Zendesk4ProcessExecutionTest.java
  src/test/resources/connector/process-execution-recoverable.json
  src/test/resources/connector/process-execution-recoveryInProgress.json
Labels: enhancement

#731 Introduce recovery related fields in Zendesk4ProcessExecution
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/connector/Zendesk4ProcessExecution.java
  gooddata-java-model/src/test/java/com/gooddata/sdk/model/connector/Zendesk4ProcessExecutionTest.java
  gooddata-java-model/src/test/resources/connector/process-execution-recoverable.json
  gooddata-java-model/src/test/resources/connector/process-execution-recoveryInProgress.json
Labels: enhancement

#732 Improve checks in release script
  release.sh
Labels: trivial

#733 Move LcmEntityFilter to model
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/lcm/LcmEntityFilter.java
  gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/lcm/LcmEntityFilterTest.groovy
  gooddata-java/src/main/java/com/gooddata/sdk/service/lcm/LcmService.java
  gooddata-java/src/test/groovy/com/gooddata/sdk/service/lcm/LcmServiceIT.groovy
Labels: backward incompatible, enhancement

#735 Register the services as Spring beans with reasonable name
  gooddata-java/src/main/java/com/gooddata/sdk/service/GoodData.java
  gooddata-java/src/test/groovy/com/gooddata/sdk/service/GoodDataBeansAsServicesIT.groovy
  gooddata-java/src/test/java/com/gooddata/sdk/service/spring/GoodDataBeansAsServicesIT.java
Labels: backward incompatible, enhancement

#740 Remove slf4j-nop version from README
  README.md
Labels: trivial

#741 Merge master and resolve conflicts
  README.md
  gooddata-java-model/src/test/resources/connector/process-execution-recoverable.json
  gooddata-java-model/src/test/resources/connector/process-execution-recoveryInProgress.json
  pom.xml
  release.sh
Labels: trivial
