Repository gooddata/gooddata-java, pull requests merged in 2019-03, with the labels that each got.

#742 Upgrade to API version 2
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/project/Project.java
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/project/Projects.java
  gooddata-java-model/src/main/resources/GoodDataApiVersion
  gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/project/ProjectsTest.groovy
  gooddata-java-model/src/test/resources/project/projects.json
  gooddata-java/src/main/java/com/gooddata/sdk/service/project/ProjectService.java
  gooddata-java/src/test/groovy/com/gooddata/sdk/service/GoodDataIT.groovy
  gooddata-java/src/test/java/com/gooddata/sdk/service/project/ProjectServiceAT.java
  gooddata-java/src/test/java/com/gooddata/sdk/service/project/ProjectServiceTest.java
Labels: backward incompatible, enhancement

#743 Raise API version to 3
  gooddata-java-model/src/main/resources/GoodDataApiVersion
  gooddata-java/src/test/groovy/com/gooddata/sdk/service/GoodDataIT.groovy
Labels: trivial

#746 Remove AFM.NativeTotalItem potentially ambiguous constructor
  gooddata-java-model/src/main/java/com/gooddata/sdk/model/executeafm/afm/NativeTotalItem.java
  gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/executeafm/ExecutionTest.groovy
  gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/executeafm/afm/AfmTest.groovy
  gooddata-java-model/src/test/groovy/com/gooddata/sdk/model/executeafm/afm/NativeTotalItemTest.groovy
Labels: backward incompatible

#747 Bump groovy to 2.5
  pom.xml
  src/test/groovy/com/gooddata/executeafm/afm/PreviousPeriodDateDataSetTest.groovy
  src/test/groovy/com/gooddata/md/visualization/VisualizationConverterTest.groovy
Labels: dependencies, trivial
