Repository gooddata/gooddata-java, pull requests merged in 2019-05, with the labels that each got.

#768 Enhance ProjectService's adding of a user to project
  gooddata-java/src/main/java/com/gooddata/sdk/service/project/ProjectService.java
  gooddata-java/src/test/java/com/gooddata/sdk/service/project/ProjectServiceAT.java
  gooddata-java/src/test/java/com/gooddata/sdk/service/project/ProjectServiceIT.java
  gooddata-java/src/test/java/com/gooddata/sdk/service/project/ProjectServiceTest.java
Labels: bug

#777 Add HTTP 500 IT for ConnectorService
  src/test/java/com/gooddata/connector/ConnectorServiceIT.java
Labels: trivial

#780 Add retry support when GD endpoint is unvailable
  README.md
  pom.xml
  src/main/java/com/gooddata/GoodData.java
  src/main/java/com/gooddata/GoodDataSettings.java
  src/main/java/com/gooddata/retry/GetServerErrorRetryStrategy.java
  src/main/java/com/gooddata/retry/RetrySettings.java
  src/main/java/com/gooddata/retry/RetryStrategy.java
  src/main/java/com/gooddata/retry/RetryableRestTemplate.java
  src/test/groovy/com/gooddata/retry/RetrySettingsTest.groovy
  src/test/groovy/com/gooddata/retry/RetryableRestTemplateTest.groovy
  src/test/java/com/gooddata/connector/ConnectorServiceIT.java
Labels: enhancement

#786 Log retried API calls
  src/main/java/com/gooddata/retry/RetryableRestTemplate.java
Labels: trivial

#789 Log retried API calls
  gooddata-java/src/main/java/com/gooddata/sdk/service/retry/RetryableRestTemplate.java
Labels: trivial
